name: clang-win-debug

on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main ]

env:
  PRESET: clang-win-debug

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: configure
      run: cmake -G "Ninja" --preset %PRESET% .
    - name: build
      run: cmake --build ./build/%PRESET% --parallel $(nproc) --target tests
    - name: run tests
      run: ./build/%PRESET%/tests/tests.exe
